### ISSUE TITLE
OTP NotBefore should use UTC time

### ISSUE THREAD

**Issue by fajo-de** [ubccr/mokey#124] opened 2023-03-18 23:09 UTC
When a user adds an OTP token, the application will set NotBefore on the token. If the server running MoKey 6.3 has a time zone other than UTC configured it will cause the wrong start date/time to be set in IPA.

This most probably is caused by MoKey using `time.Now()` instead of `time.Now().UTC()` when setting the start time.

**Comment by fajo-de** [comment] 2023-03-19 08:51
As a workaround simply add the below to the service config /etc/default/mokey:

`TC=UTC`

**Comment by aebruno** [comment] 2024-10-23 19:52
I'm unable to reproduce this. When mokey adds an OTP token the date time is set correctly in freeipa. The resulting token will look like this:

```
  Unique ID: xxxx
  Type: TOTP
  Description: mytoken
  Owner: username
  Validity start: 20241023153503Z
```

It does not appear freeipa supports timezones in the validity start (not before) dates. For example:

```
$ ipa otptoken-add --not-before='2024-10-23T19:43:08-04:00'
ipa: ERROR: invalid 'not_before': does not match any of accepted formats: %Y%m%d%H%M%SZ, %Y-%m-%dT%H:%M:%SZ, %Y-%m-%dT%H:%MZ, %Y-%m-%dZ, %Y-%m-%d %H:%M:%SZ, %Y-%m-%d %H:%MZ
```

Mokey and freeipa will use the timezone of the system, so just ensure both freeipa servers and mokey server are set to the same timezone. Mokey uses `time.Now()` which returns the current local time. Closing this out but feel free to re-open if I'm missing something here. Thanks!

**Closed by aebruno** 2024-10-23 19:52 UTC

**Comment by fajo-de** [comment] 2024-10-23 21:33
Hi, both, Mokey and IPA servers are configured to use CE(S)T and the issue was reproducable. What TZ where your server running under when you tried to reproduce this issue?

**Comment by aebruno** [comment] 2024-10-24 00:22
Tested with EDT. But not sure this matters as the timezone is not stored in freeipa.
